// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const SquareVerifier = artifacts.require("SquareVerifier");
const proof = require('./proof.json');

// // Test verification with correct proof
// // - use the contents from proof.json generated from zokrates steps

contract('SquareVerifier', async (accounts) => {
    it('verifyTx', async () => {
        const squareVerifier = await SquareVerifier.deployed();
        const result = await squareVerifier.verifyTx(proof.proof, proof.inputs);
        assert.equal(result, true, 'verification failed');
    });
});
    
// Test verification with incorrect proof
